---
# General cluster settings
external_interface: eth0
external_ip_address: DHCP
external_network_gateway: "{{ ansible_facts[external_interface].ipv4.address }}"
management_interface: eth1
management_ip_address: 10.142.255.254
management_network_baseaddress: 10.142.0.0
external_name_servers: [10.2.200.200]
timezone: Europe/Amsterdam
license:
  country: NL
  state: Amsterdam
  locality: Amsterdam
  organization: Bright Computing
  organizational_unit: Engineering
  cluster_name: BrightCluster
  mac: "{{ ansible_default_ipv4.macaddress }}"
