---
# Cluster credentials
product_key: "{{ lookup('env', 'PRODUCT_KEY') }}"
db_cmd_password: s3cret!db_cmd_password
slurm_user_pass: s3cret!slurm_user_pass
ldap_root_pass: s3cret!ldap_root_pass
ldap_readonly_pass: s3cret!ldap_readonly_pass
